// Grammar registry: the languages with parsers installed under
// lib/<os>/<arch>/grammars/ by tools/build. The generated binding packages
// are imported through the "grammars:" collection (wired in the justfile);
// grammars_table.odin carries the imports and the GRAMMARS table itself
// (regenerated by scripts/extract_table), and this file holds the
// entry shape and the lookups the rest of the code consumes. Consumers
// materialize the table before indexing (the compiler rejects variable
// indexing straight into constant data).
package ts

import "core:slice"
import "core:strings"

Grammar_Entry :: struct {
	name:       string,
	aliases:    []string,
	extensions: []string,              // file extensions this grammar serves (".go", ...)
	language:   proc "c" () -> rawptr, // generated bindings use the C convention
	tags_query: string,                // outline/tags source; "" when the grammar ships none
}

// registry_lookup resolves a language name (or alias, case-insensitive)
// to the INDEX of its grammar entry — the handle the rest of the
// registry API deals in.
registry_lookup :: proc(name: string) -> (idx: int, ok: bool) {
	table := GRAMMARS
	for i in 0..<len(table) {
		if name_eq(name, table[i].name) {
			return i, true
		}
		aliases := table[i].aliases
		for j in 0..<len(aliases) {
			if name_eq(name, aliases[j]) {
				return i, true
			}
		}
	}
	return -1, false
}

// registry_supported reports whether a language name resolves to a
// built-in grammar (used by callers that only need existence).
registry_supported :: proc(name: string) -> bool {
	_, ok := registry_lookup(name)
	return ok
}

// registry_language resolves a grammar index to its tree-sitter language.
// false when the binding is a platform stub: tools/build writes a
// nil-returning stub binding when a grammar's C sources fail to compile
// with the local toolchain (an MSVC-hostile scanner, say), so every
// grammars:<name> package the registry table imports still resolves —
// callers report the language as unavailable instead of handing a nil
// TSLanguage to the parser/query layer.
registry_language :: proc(idx: int) -> (lang: Language, ok: bool) {
	// Materialize the registry locally before indexing (the compiler
	// rejects variable indexing straight into constant data).
	table := GRAMMARS
	ptr := table[idx].language()
	if ptr == nil {
		return Language(nil), false
	}
	return Language(ptr), true
}

// suffix_starts collects the start offsets of up to 4 dot-suffixes of a
// base name, scanning from the end: starts[0] is the shortest (the last
// dot), higher indices are longer suffixes that callers check first.
suffix_starts :: proc(base: string) -> (starts: [4]int, n: int) {
	for i := len(base) - 1; i > 0 && n < 4; i -= 1 {
		if base[i] == '.' {
			starts[n] = i
			n += 1
		}
	}
	return
}

// registry_lookup_by_extension resolves a file name to the grammar serving
// its extension ("" when no grammar claims it). Up to four dot-suffixes of
// the base name are tried longest-first (".blade.php" before ".php"),
// case-insensitive.
registry_lookup_by_extension :: proc(filename: string) -> (idx: int, ok: bool) {
	table := GRAMMARS
	base := file_base_name(filename)
	starts, n := suffix_starts(base)
	for s := n - 1; s >= 0; s -= 1 {
		ext := base[starts[s]:]
		for i in 0..<len(table) {
			exts := table[i].extensions
			for j in 0..<len(exts) {
				if name_eq(exts[j], ext) {
					return i, true
				}
			}
		}
	}
	return -1, false
}

// Linguist_Claim pairs a Linguist detection key (an exact filename like
// "Makefile" or a shebang interpreter like "python3") with the grammar
// name it resolves to. The tables themselves are generated into
// grammars_table.odin; consumers materialize them before indexing, like
// GRAMMARS.
Linguist_Claim :: struct {
	key:     string,
	grammar: string,
}

// registry_lookup_by_filename resolves a file name by Linguist exact
// filename claim (Makefile, Dockerfile, .bashrc, ...). This is the most
// specific tier and is checked before extensions, so ".tmux.conf"
// resolves to bash rather than the generic ".conf". Case-sensitive, like
// the Linguist table itself (which carries the ".Justfile"/".JUSTFILE"
// variants as separate rows) — and byte-sorted by the generator, so the
// lookup is a binary search (the linear scan once ran as the first tier
// of every crawled file's detection).
registry_lookup_by_filename :: proc(filename: string) -> (idx: int, ok: bool) {
	base := file_base_name(filename)
	claims := LINGUIST_FILENAMES
	pos, found := slice.binary_search_by(claims, base, claim_key_order)
	if found {
		return registry_lookup(claims[pos].grammar)
	}
	return -1, false
}

// claim_key_order compares a claim's key against a probe string in byte
// order — the order the generator's sort_claims produced.
claim_key_order :: proc(c: Linguist_Claim, probe: string) -> slice.Ordering {
	if c.key == probe {
		return .Equal
	}
	if c.key < probe {
		return .Less
	}
	return .Greater
}

// registry_lookup_by_shebang resolves the first line of a file's contents
// to a grammar via its shebang interpreter ("#!/usr/bin/env python3" ->
// python, "#!/bin/sh" -> bash). "" when the line is not a shebang or the
// interpreter has no registered grammar.
registry_lookup_by_shebang :: proc(first_line: string) -> (idx: int, ok: bool) {
	interp := shebang_interpreter(first_line)
	if interp == "" {
		return -1, false
	}
	claims := LINGUIST_INTERPRETERS
	for i in 0..<len(claims) {
		if name_eq(claims[i].key, interp) {
			return registry_lookup(claims[i].grammar)
		}
	}
	return -1, false
}

// registry_detect runs the filename ladder for callers without file
// contents: the exact-filename tier first, then the extension scan.
registry_detect :: proc(filename: string) -> (idx: int, ok: bool) {
	if fi, fok := registry_lookup_by_filename(filename); fok {
		return fi, true
	}
	return registry_lookup_by_extension(filename)
}

// registry_extension_map prebuilds the extension tier for sources that
// detect files in bulk (the crawl, one probe per file per walk): a map
// from lowercased extension to grammar index, resolved first-wins in
// table order at build time — the same precedence the linear scan
// applies, because the table is alphabetical by grammar name. Constant
// size (~one entry per claimed extension); keys are cloned on insert and
// owned by the map's allocator (free the map with a bare delete).
registry_extension_map :: proc(a := context.allocator) -> (m: map[string]int) {
	m = make(map[string]int, 256, a)
	table := GRAMMARS
	for i in 0..<len(table) {
		exts := table[i].extensions
		for j in 0..<len(exts) {
			lower := strings.to_lower(exts[j], context.temp_allocator)
			if _, exists := m[lower]; !exists {
				m[strings.clone(lower, a)] = i
			}
		}
	}
	return m
}

// registry_detect_with_map is registry_detect's filename ladder for
// holders of a prebuilt extension map (see registry_extension_map): the
// exact-filename tier first, then up to four dot-suffixes longest-first
// against the map. The lowercase fold of each probed suffix is
// intra-procedure scratch on `a`.
registry_detect_with_map :: proc(ext_map: map[string]int, filename: string, a := context.allocator) -> (idx: int, ok: bool) {
	if fi, fok := registry_lookup_by_filename(filename); fok {
		return fi, true
	}
	base := file_base_name(filename)
	starts, n := suffix_starts(base)
	for s := n - 1; s >= 0; s -= 1 {
		ext := strings.to_lower(base[starts[s]:], a)
		if i, found := ext_map[ext]; found {
			return i, true
		}
	}
	return -1, false
}

// registry_detect_content runs the full ladder for callers holding the
// file's contents: filename tiers first, then the shebang fallback for
// extensionless scripts.
registry_detect_content :: proc(filename: string, contents: string) -> (idx: int, ok: bool) {
	if di, dok := registry_detect(filename); dok {
		return di, true
	}
	return registry_lookup_by_shebang(first_line_of(contents))
}

// shebang_interpreter extracts the interpreter name from a shebang line
// ("#!/usr/bin/env python3" -> "python3", "#!/usr/bin/perl" -> "perl",
// "#!/usr/bin/env -S awk -f" -> "awk"), "" when the line is not a
// shebang. The env form skips flags (-S, -u) and VAR=value assignments.
shebang_interpreter :: proc(line: string) -> string {
	t := strings.trim_space(line)
	if !strings.has_prefix(t, "#!") {
		return ""
	}
	rest := strings.trim_space(t[2:])
	fields := strings.fields(rest, context.temp_allocator)
	if len(fields) == 0 {
		return ""
	}
	binary := file_base_name(fields[0])
	if binary == "env" {
		for f in fields[1:] {
			if strings.has_prefix(f, "-") {
				continue
			}
			if strings.contains(f, "=") {
				continue
			}
			return f
		}
		return ""
	}
	return binary
}

// first_line_of returns the contents up to the first newline, capped so a
// pathological single-line file cannot drag the whole buffer through
// shebang parsing.
first_line_of :: proc(contents: string) -> string {
	limit := min(len(contents), 256)
	for i in 0..<limit {
		if contents[i] == '\n' {
			return contents[:i]
		}
	}
	if len(contents) <= 256 {
		return contents
	}
	return contents[:256]
}

// file_base_name returns the final path component of a file name (both
// separators accepted, mirroring the extension scan's stop condition).
file_base_name :: proc(filename: string) -> string {
	sep := -1
	for i := len(filename) - 1; i >= 0; i -= 1 {
		if filename[i] == '/' || filename[i] == '\\' {
			sep = i
			break
		}
	}
	return filename[sep+1:]
}

name_eq :: proc(a, b: string) -> bool {
	if len(a) != len(b) {
		return false
	}
	for i in 0..<len(a) {
		ca, cb := a[i], b[i]
		if ca >= 'A' && ca <= 'Z' {
			ca = ca + ('a' - 'A')
		}
		if cb >= 'A' && cb <= 'Z' {
			cb = cb + ('a' - 'A')
		}
		if ca != cb {
			return false
		}
	}
	return true
}
